### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by nmeum** [ibara/oed#12]
I maintain an oed package for Alpine Linux, for this package I used the tagged release tarballs from GitHub as a source. It seems that commit 314e3f995c193aa316315a423ab865f5afe73e25 upgraded the `oed` source code to OpenBSD 7.1. Would it be possible to tag a new release with these changes so I can update our Alpine package?

Thanks and thanks a lot for maintaining this port in general!

**Comment by ibara** [comment]
Yes, I can do this. Give me until the end of the day (NY time) today.

**Comment by nmeum** [comment]
> Yes, I can do this. Give me until the end of the day (NY time) today.

Friendly reminder that a tag hasn't been created yet, just in case you simply forgot about this :)

**Comment by ibara** [comment]
Done.
