### ISSUE TITLE
REG_STARTEND flag missing on musl, AIX and likely more

### ISSUE THREAD

**Issue by xorhash** [ibara/oed#2]
According to [OpenBSD regex(3)](https://man.openbsd.org/regexec#REG_STARTEND), the `REG_STARTEND` flag is not specified by POSIX. This would be a non-issue if it could be ignored in practice, but I recently found out that musl [does not implement REG_STARTEND and appears to have no immediate plans to do so](https://marc.info/?l=musl&m=154492544407519&w=2).

I'm not sure what a proper fix would consist of. I could see any of these:

1. Change the claim in `README.md` that “any minimally `POSIX` operating system” should be able to run OpenED.
2. Add a note that musl is known broken and won't be fixed.
3. Take OpenBSD's lib/libc/regex instead of using the operating system's. This would have the extra benefit of never having issues with mutually incompatible regex implementation.
4. Try to push musl upstream to implement `REG_STARTEND` and hope nobody runs into this issue on other platforms such as [AIX](https://public-inbox.org/git/20170503135430.7785-1-avarab@gmail.com/), which also suffers from this feature deficiency.
5. Try to work around not having `REG_STARTEND` in `sub.c` somehow, which is the only affected calling site. That's fairly complex and requires fairly deep understanding of the involved code and regex, and I'm definitely not up for doing that myself.

**Comment by ibara** [comment]
Option 3 makes the most sense.
