### ISSUE TITLE
oed 6.6 & master `cannot open temp file'

### ISSUE THREAD

**Issue by JNeitzel** [ibara/oed#4]
Hi @ibara,

@JNeitzel here. oed gives the noted error message when running under Termux. So, it can't open the scratch file. Reason? /tmp doesn't exist; .../usr/tmp does. The following patch fixes the problem:

```
--- buf.c.orig  2019-10-03 22:51:42.000000000 -0400
+++ buf.c       2020-03-01 08:45:34.304472124 -0500
@@ -197,7 +197,7 @@

 extern int newline_added;

-#define SCRATCH_TEMPLATE      "/tmp/ed.XXXXXXXXXX"
+#define SCRATCH_TEMPLATE      "/data/data/com.termux/files/usr/tmp/ed.XXXXXXXXXX"
 static char sfn[sizeof(SCRATCH_TEMPLATE)+1] = "";/* scratch file name */

 /* open_sbuf: open scratch file */
```

.

That fixes the immediate problem without any ifdefs. :)

-- 
Cheers,
Jeff Neitzel

**Comment by ibara** [comment]
Hi Jeff --

That patch by itself won't work since it will break everywhere else.

I wonder if there's some way to detect Termux via configure. Then we can add the appropriate #ifdefs (unavoidable here, sadly).

**Comment by JNeitzel** [comment]
Yes, there is a way to detect Termux, and #ifdef it as needed. For example:

```
termux>$ pwd
/data/data/com.termux/files/usr/include/sys

termux>$ grep TERMUX *.h
cdefs.h:#define __TERMUX__ 1
cdefs.h:#define __TERMUX_PREFIX__ "/data/data/com.termux/files/usr"
```

Does that help?

**Comment by JNeitzel** [comment]
And here it is as a patch.

```
--- buf.c.orig  2020-03-01 13:09:35.349990807 -0500
+++ buf.c       2020-03-04 15:22:30.327802587 -0500
@@ -197,7 +197,11 @@

 extern int newline_added;

+#ifdef __TERMUX__
+#define SCRATCH_TEMPLATE      "/data/data/com.termux/files/usr/tmp/ed.XXXXXXXXXX"
+#else
 #define SCRATCH_TEMPLATE      "/tmp/ed.XXXXXXXXXX"
+#endif
 static char sfn[sizeof(SCRATCH_TEMPLATE)+1] = "";/* scratch file name */

 /* open_sbuf: open scratch file */
```

-- 
Jeff

**Comment by ibara** [comment]
Yup. That will have to do. I'll commit that version shortly.

**Comment by JNeitzel** [comment]
Cool. Go for it. I run the latest Termux version (Termux-0.92) BTW. Meaning, I keep it up to date.

**Comment by JNeitzel** [comment]
I finalized the patch so we aren't hard-coding long Termux fs path strings "..."; it just makes me feel better is all, if that makes sense. In any case, see below for the updated patch.

```
--- buf.c.orig  2020-03-01 13:09:35.349990807 -0500
+++ buf.c       2020-03-05 08:09:56.755843504 -0500                                                 @@ -197,7 +197,11 @@
                                                   extern int newline_added;

+#ifdef __TERMUX__
+#define SCRATCH_TEMPLATE      __TERMUX_PREFIX__/**/"/tmp/ed.XXXXXXXXXX"
+#else
 #define SCRATCH_TEMPLATE      "/tmp/ed.XXXXXXXXXX"
+#endif
 static char sfn[sizeof(SCRATCH_TEMPLATE)+1] = "";/* scratch file name */

 /* open_sbuf: open scratch file */
```

:)

**Comment by JNeitzel** [comment]
Sorry, the updated patch got mucked up. It's the copying & pasting I suppose, but the key change is...

```
__TERMUX_PREFIX__/**/"/tmp/ed.XXXXXXXXXX"
```

... Sorry again, but that change is the long and short of it .

**Comment by JNeitzel** [comment]
See updated patch below.

```
--- buf.c.orig  2020-03-01 13:09:35.349990807 -0500
+++ buf.c       2020-03-06 12:04:10.582437735 -0500
@@ -197,7 +197,12 @@

 extern int newline_added;

-#define SCRATCH_TEMPLATE      "/tmp/ed.XXXXXXXXXX"
+#ifdef __TERMUX__
+#define SCRATCH_TEMPLATE __TERMUX_PREFIX__/**/"/tmp/ed.XXXXXXXXXX"
+#else
+#define SCRATCH_TEMPLATE "/tmp/ed.XXXXXXXXXX"
+#endif
+
 static char sfn[sizeof(SCRATCH_TEMPLATE)+1] = "";      /* scratch file name */

 /* open_sbuf: open scratch file */
```

:)

**Comment by JNeitzel** [comment]
@ibara, you'll find the updated patch at https://jan.etsh.nl/oed-master-diffs/oed-master-buff_c.diff .

It applies cleanly. oed works well with it instead of not working at all. It is simpler than trying to copy & paste it. Now, I see that I could have attached it here by dragging & dropping it. Well, I'm done. Thanks for oed :)

Cheers,
Jeff @JNeitzel

**Comment by ibara** [comment]
I ended up going with the hardcoded path. It will serve as a warning if things ever change with Termux.

**Comment by JNeitzel** [comment]
Ok, gotcha on that.
